### ISSUE TITLE
[BUG] pip install from git (master) not working on Colab tutorials

### ISSUE THREAD

**Issue by dvsrepo** [recognai/biome-text#438]
# Describe the bug

`pip install` fails.

## To Reproduce
Go to and run install cell:  https://colab.research.google.com/github/recognai/biome-text/blob/master/docs/docs/documentation/tutorials/1-Training_a_text_classifier.ipynb

It might be related to recent setup.py changes.

## Expected behavior

Most important is: can we make pip install from source work on Collab with recent changes?

Most immediate solutions, either:

- Review all tutorials and modify install git url pointing to the version/commit where they were functioning.
- At least for the first, it works with the 1.0 release on PyPi: `pip install biome-text`

This is related to a broader issue, already discussed, we need to anchor tutorials either to a specific release (we actually should create releases more often) or using git commit urls to make sure they are installed with the right version.

**Comment by dcfidalgo** [comment]
Just merged PR #439 that should fix the tutorial. The issue was that we now require a very new pip version for the installation to take advantage of the new dependency resolver. Not sure why it did not print the corresponding error message that we have  in our `setup.py` ... In the soon to come version 20.3 the new resolver is supposed to become the standard, so maybe colab will update the default version once it is released.

Yes, i agree tutorials should be linked to releases! For now I will try to add git commit urls as an intermediate solution.

**Comment by dvsrepo** [comment]
Cool!!
